"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueensideBlack = exports.KingsideBlack = exports.QueensideWhite = exports.KingsideWhite = exports.NotGHFile = exports.NotABFile = exports.NotHFile = exports.NotAFile = void 0;
exports.NotAFile = 0xfefefefefefefefen;
exports.NotHFile = 0x7f7f7f7f7f7f7f7fn;
exports.NotABFile = 0xfcfcfcfcfcfcfcfcn;
exports.NotGHFile = 0x3f3f3f3f3f3f3f3fn;
exports.KingsideWhite = 0x6000000000000000n;
exports.QueensideWhite = 0xe00000000000000n;
exports.KingsideBlack = 0x60n;
exports.QueensideBlack = 0xen;
